### ISSUE TITLE
XML is not working

### ISSUE THREAD

**Issue by LukasHolzner** [toohoo/thofaq#13]
Recently, I tried to use XML within a `[code]` tag. Unfortunately, all XML-tags were deleted (probably to prevent injections). I could solve it with replacing all `<` with `&lt;` but within a XML file this can be really annoying. Is it possible to support XML with the `[code]` tag or to create a new tag like `[xml]`?

**Comment by toohoo** [comment]
Hello Lukas,
CODE is simply monospaced font and PRE is for preformated text with line breaks and monospaced font. 
For you may be able to use XML, I will open a branch and do the changes there.
For XML use pseudo markup element [XML].
I will let you know, when I'm done.
best regards, Thomas

**Comment by toohoo** [comment]
Hello Lukas,
I have done the changes and merged the branch xml_tag back to master. Please review, if this fulfills your requirements. And let me know please.
Regards, Thomas
PS: Take [xml] ... [/xml]

**Comment by LukasHolzner** [comment]
Thanks Thomas! Looks good, but unfortunately I couldn't test it yet as I have trouble setting up the FAQ on my linux machine (see #15 and #16)

**Comment by toohoo** [comment]
Please see issues (see #15 and #16) and please test if it works now. Watching your response :-)

**Comment by LukasHolzner** [comment]
I also tried the new XML tag. It works but if you use HTML inside the tag then it is rendered, e.g.
```
[xml]
<b>Test</b>
[/xml]
```
will end up as

**Test**

I don't think this is a problem, but I wanted to mention it.
I think this issue can be closed but because of the side effect mentioned above I leave it to you.

**Comment by toohoo** [comment]
This is overlapping with the standard markup of BBCode. If you input < p >< /p > on editing in an existing or new FAQ-question it is replaced with [ p ][ /p ] . This is to give the possibility to input the standard HTML-tags.
I have to rethink if and how this could be avoided. 
Thanks so far, I will answer.

**Comment by toohoo** [comment]
Hello Lukas,
I have done some restructuring. XML blocks now should be masked before all other reformating. Please try, if it works now for you. This change should be changed only in `webtools.pl` .

**Comment by LukasHolzner** [comment]
Hi Thomas,
yes I checked the `<b>` Tag again and it is now displayed as `<b>` inside the `[xml]` Tag. Thanks.
