### ISSUE TITLE
Non-influencing entry in the error.log

### ISSUE THREAD

**Issue by LukasHolzner** [toohoo/thofaq#16]
While searching for the solution of the problem of editing described in #15 I found another entry in the apache `error.log`. But, this error does not influence the usage as far as I can tell.
```
Can't exec "cd": No such file or directory at /var/www/html/faq/cgi-bin/thpl.pl line 793.
Use of uninitialized value $_aktdir in scalar chop at /var/www/html/faq/cgi-bin/thpl.pl line 794.
Use of uninitialized value $_aktdir in concatenation (.) or string at /var/www/html/faq/cgi-bin/thpl.pl line 796.
Subroutine printListe redefined at /var/www/html/faq/cgi-bin/webtools.pl line 2414.
Subroutine printHash redefined at /var/www/html/faq/cgi-bin/webtools.pl line 2447.
```
Maybe this is interesting for you to know.

**Comment by toohoo** [comment]
Yes, that's probably the only single point I did oversee to make a difference between Win and Linux. I will try to fix this. It seems to be a solution to look for a system specific attribute or variable like PATH or maybe environment of running webserver and then on Win systems make another call as on Linux systems.

**Comment by toohoo** [comment]
I did extend the part of the script. This should work now, please test. Would appreciate feedback. Thanks

**Comment by LukasHolzner** [comment]
I think you fixed the errors above but when I click on _All Categories_ I get following lines in the `error.log`
```
Subroutine printListe redefined at /var/www/html/faq/cgi-bin/webtools.pl line 2414.
Subroutine printHash redefined at /var/www/html/faq/cgi-bin/webtools.pl line 2447.
Use of uninitialized value within %kat in concatenation (.) or string at /var/www/html/faq/cgi-bin/webtools.pl line 985.
```
I don't think this is severe but maybe you want to check.

**Comment by LukasHolzner** [comment]
I get the same entries in the log when I switch back from _edit_ mode to _normal_ mode and when I show the _hashtags_ and _hashclouds_.

**Comment by toohoo** [comment]
The `Subroutine ... redefined` issue is known so far. Could possibly be avoided. Does disturb nothing.
The `use of uninitialized value` is possible to avoid. I will look for it.
Thanks so far

**Comment by toohoo** [comment]
Hello Lukas,
I did add some changes. I would much appreciate if you would mind testing the changes and send me response.
Have a great evening, Thomas
PS: As always, do a file to file compare or simply remove the Windows shebang.

**Comment by LukasHolzner** [comment]
Hi Thomas,
I just checked out your latest changes. I do not get any errors anymore. Thanks for your effort and explanations.
Best regards
Lukas
